modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="http://my.issue.tracker/"

[[mods]]
modId="haan"
version="1.0.0"
displayName="Harvesting Animals"
displayURL="https://www.curseforge.com/minecraft/mc-mods/crop-eating-animals"
credits="Thanks for this example mod goes to Java"
authors="KidsDontPlay"
description='''
Animals eat your crops
'''

[[dependencies.haan]]
    modId="forge"
    mandatory=true
    versionRange="[28,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.haan]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4,1.15)"
    ordering="NONE"
    side="BOTH"
